version: "3"
services:
  mongodb:
    container_name: "nexr"
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=./docker/data
    volumes:
      - ./docker/data:/data/db
    ports:
      - 27017:27017
    command: mongod
